// İngilizce dil desteği: içerik sözlüğü (TR -> EN) + arayüz metinleri
// Çeviri bulunamazsa uygulama Türkçe metne geri döner.

const EN_SOZLUK = {
  // ----- Hafta başlıkları -----
  "Selamlaşma ve Temeller": "Greetings & Basics",
  "Günlük Hayat": "Daily Life",
  "İletişim Kurma": "Communicating",
  "Akıcılığa Doğru": "Towards Fluency",
  "İş Hayatı (Ofis)": "Work Life (Office)",
  "Tekrar ve Pekiştirme": "Review & Practice",
  "Serbest Konuşma Pratiği": "Free Speaking Practice",
  "Genel Değerlendirme": "Final Review",
  "Hafta 1-3 kelimelerini quiz ve konuşma pratiğiyle pekiştir. Çevirmen sekmesinde kendi cümlelerini kur, sesli oku ve telaffuzunu test et.":
    "Reinforce weeks 1-3 vocabulary with quizzes and speaking practice. Build your own sentences in the Translator tab, listen and test your pronunciation.",
  "Her gün 5 cümleyi mikrofonla %70+ doğrulukla okumayı hedefle. Mini diyalogları ezbere söylemeye çalış.":
    "Aim to read 5 sentences a day with 70%+ accuracy using the mic. Try to recite the mini dialogues by heart.",
  "Tüm dersleri karışık quiz modunda çöz. %80+ başarıyla bitirince temel seviyeyi tamamlamış olursun. Mabruuk! (Tebrikler!)":
    "Take mixed quizzes covering all lessons. Score 80%+ and you've completed the basic level. Mabruuk! (Congratulations!)",

  // ----- Ders başlıkları -----
  "⭐ Süper Kelimeler — Her Cümlede Duyacakların": "⭐ Super Words — You'll Hear These Everywhere",
  "Merhaba Demek": "Saying Hello",
  "Vedalaşma ve Nezaket": "Goodbyes & Politeness",
  "🙏 'Rica Ederim' Demenin 8 Yolu": "🙏 8 Ways to Say 'You're Welcome'",
  "Kendini Tanıtma": "Introducing Yourself",
  "Evet, Hayır ve Tepkiler": "Yes, No & Reactions",
  "Sayılar 1-10": "Numbers 1-10",
  "Soru Kelimeleri": "Question Words",
  "Yiyecek ve İçecek": "Food & Drink",
  "Restoranda": "At the Restaurant",
  "Alışveriş ve Pazarlık": "Shopping & Bargaining",
  "Sayılar 11-100 ve Zaman": "Numbers 11-100 & Time",
  "Ulaşım ve Yön": "Transport & Directions",
  "Aile": "Family",
  "Duygular ve Haller": "Feelings & States",
  "Günlük Fiiller": "Everyday Verbs",
  "Hayatta Kalma Cümleleri": "Survival Sentences",
  "Geçmiş Zaman": "Past Tense",
  "Gelecek Zaman ve Planlar": "Future Tense & Plans",
  "Sohbet Kalıpları": "Conversation Phrases",
  "Her Yerde Geçen Kalıplar": "Phrases That Work Everywhere",
  "Mini Diyaloglar": "Mini Dialogues",
  "İşte İlk Gün": "First Day at Work",
  "Toplantı ve Randevu": "Meetings & Appointments",
  "Ofiste Günlük İletişim": "Daily Office Communication",
  "Telefon ve Yazışma": "Phone & Messaging",
  "İş Nezaketi ve Kalıplar": "Work Etiquette & Phrases",

  // ----- Hafta 1 -----
  "Hadi / gidelim": "Come on / let's go",
  "Tamam / bitti / yeter": "Done / finished / enough",
  "Tamam / olur / anlaştık": "OK / fine / deal",
  "Boş ver / olsun / kusura bakma": "Never mind / it's OK / sorry",
  "İnşallah": "God willing (hopefully)",
  "Çok şükür": "Thank God",
  "Canım / dostum (habibi!)": "My dear / buddy (habibi!)",
  "Böyle / öyle / işte": "Like this / like that / so",
  "Sadece / ama / yeter": "Just / but / enough",
  "Biraz / azıcık": "A little / a bit",
  "Merhaba": "Hello",
  "Hoş geldin": "Welcome",
  "Günaydın": "Good morning",
  "Günaydın (cevap)": "Good morning (reply)",
  "İyi akşamlar": "Good evening",
  "Nasılsın? (erkeğe denir)": "How are you? (to a man)",
  "Nasılsın? (kadına denir)": "How are you? (to a woman)",
  "İyiyim (erkek söyler)": "I'm fine (man speaking)",
  "İyiyim (kadın söyler)": "I'm fine (woman speaking)",
  "İyi / tamam / harika": "Good / OK / great",
  "Güle güle": "Goodbye",
  "Hoşça kal (gündelik)": "Bye (casual)",
  "Teşekkürler": "Thank you",
  "Bin teşekkür": "A thousand thanks",
  "Rica ederim": "You're welcome",
  "Lütfen (erkeğe denir)": "Please (to a man)",
  "Affedersiniz / lütfen": "Excuse me / please",
  "Üzgünüm (erkek söyler)": "I'm sorry (man speaking)",
  "Üzgünüm (kadın söyler)": "I'm sorry (woman speaking)",
  "Sorun değil": "No problem",
  "Rica ederim (en yaygın)": "You're welcome (most common)",
  "Rica ederim / pardon": "You're welcome / pardon",
  "Rica ederim, baş üstüne (çok kibar)": "You're most welcome (very polite)",
  "Rica ederim / her zaman hizmetindeyim": "You're welcome / at your service",
  "Rica ederim / takma kafana": "You're welcome / don't worry about it",
  "Rica ederim, bu benim görevim": "You're welcome, it's my duty",
  "Buyur (erkeğe denir)": "Here you go (to a man)",
  "Buyur (kadına denir)": "Here you go (to a woman)",
  "Sağ ol / eline sağlık (erkeğe denir)": "Thanks / bless you (to a man)",
  "Allah senden razı olsun (teşekküre cevap)": "May God reward you (reply to thanks)",
  "Ben": "I / me",
  "Sen (erkeğe denir)": "You (to a man)",
  "Sen (kadına denir)": "You (to a woman)",
  "Benim adım": "My name is",
  "Adın ne? (erkeğe sorulur)": "What's your name? (asked to a man)",
  "Ben Türkiye'denim": "I'm from Turkey",
  "Ben Türküm (erkek söyler)": "I'm Turkish (man speaking)",
  "Ben Türküm (kadın söyler)": "I'm Turkish (woman speaking)",
  "Nerelisin?": "Where are you from?",
  "Memnun oldum": "Nice to meet you",
  "Evet": "Yes",
  "Hayır": "No",
  "Tabii ki": "Of course",
  "Belki": "Maybe",
  "Olabilir / mümkün": "Possible / maybe",
  "Bilmiyorum (erkek söyler)": "I don't know (man speaking)",
  "Bilmiyorum (kadın söyler)": "I don't know (woman speaking)",
  "Gerçekten mi?": "Really?",
  "Ciddi misin?": "Are you serious?",
  "Peki / o zaman": "Well / then",
  "Bir (1)": "One (1)",
  "İki (2)": "Two (2)",
  "Üç (3)": "Three (3)",
  "Dört (4)": "Four (4)",
  "Beş (5)": "Five (5)",
  "Altı (6)": "Six (6)",
  "Yedi (7)": "Seven (7)",
  "Sekiz (8)": "Eight (8)",
  "Dokuz (9)": "Nine (9)",
  "On (10)": "Ten (10)",

  // ----- Hafta 2 -----
  "Ne?": "What?",
  "Nerede?": "Where?",
  "Ne zaman?": "When?",
  "Neden?": "Why?",
  "Nasıl?": "How?",
  "Kim?": "Who?",
  "Kaç tane? / Ne kadar?": "How many? / How much?",
  "Kaça? (fiyat)": "How much? (price)",
  "Bu ne?": "What's this?",
  "Tuvalet nerede?": "Where is the bathroom?",
  "Yemek": "Food",
  "Su": "Water",
  "Çay": "Tea",
  "Kahve": "Coffee",
  "Ekmek": "Bread",
  "Tavuk": "Chicken",
  "Et": "Meat",
  "Balık": "Fish",
  "Açım (erkek söyler)": "I'm hungry (man speaking)",
  "Susadım (erkek söyler)": "I'm thirsty (man speaking)",
  "Menü lütfen": "The menu, please",
  "İstiyorum (erkek söyler)": "I want (man speaking)",
  "İstiyorum (kadın söyler)": "I want (woman speaking)",
  "Hesap lütfen": "The bill, please",
  "Lezzetli": "Delicious",
  "Çok güzel": "Very nice",
  "Bir tane daha": "One more",
  "Şekersiz": "Without sugar",
  "Afiyet olsun": "Enjoy your meal",
  "Bu kaça?": "How much is this?",
  "Çok pahalı": "Too expensive",
  "Ucuz": "Cheap",
  "Para": "Money",
  "Riyal": "Riyal",
  "Bakabilir miyim?": "Can I take a look?",
  "Bunu alacağım": "I'll take this",
  "Bir şey istemiyorum": "I don't want anything",
  "Son fiyat mı?": "Is that the final price?",
  "Bu çok fazla": "That's too much",
  "On bir (11)": "Eleven (11)",
  "On iki (12)": "Twelve (12)",
  "Yirmi (20)": "Twenty (20)",
  "Otuz (30)": "Thirty (30)",
  "Elli (50)": "Fifty (50)",
  "Yüz (100)": "Hundred (100)",
  "Bugün": "Today",
  "Yarın": "Tomorrow",
  "Dün": "Yesterday",
  "Şimdi": "Now",

  // ----- Hafta 3 -----
  "Taksi": "Taxi",
  "Düz git / direkt": "Go straight / direct",
  "Sağ": "Right",
  "Sol": "Left",
  "Burada": "Here",
  "Orada": "There",
  "Yakın": "Near",
  "Uzak": "Far",
  "Burada dur": "Stop here",
  "...'e gidiyorum": "I'm going to...",
  "Babam": "My father",
  "Annem": "My mother",
  "Erkek kardeşim": "My brother",
  "Kız kardeşim": "My sister",
  "Kocam": "My husband",
  "Karım": "My wife",
  "Oğlum": "My son",
  "Kızım": "My daughter",
  "Arkadaşım": "My friend",
  "Mutlu (erkek için)": "Happy (for a man)",
  "Üzgün / kırgın": "Sad / upset",
  "Yorgun / hasta": "Tired / unwell",
  "Meşgul": "Busy",
  "Hasta": "Sick",
  "Sıcak (hava)": "Hot (weather)",
  "Soğuk": "Cold",
  "Korkmuş": "Scared",
  "Çok sevinçliyim": "I'm very happy",
  "Takma kafana": "Don't worry about it",
  "Yiyorum": "I eat / I'm eating",
  "İçiyorum": "I drink / I'm drinking",
  "Uyuyorum": "I sleep / I'm sleeping",
  "Çalışıyorum": "I work / I'm working",
  "Gidiyorum": "I go / I'm going",
  "Geliyorum": "I come / I'm coming",
  "Konuşuyorum": "I speak / I'm speaking",
  "Anlıyorum": "I understand",
  "Anlamıyorum": "I don't understand",
  "Seviyorum": "I love",
  "Yavaş konuşabilir misin?": "Can you speak slowly?",
  "Tekrar lütfen": "Again, please",
  "Arapça öğreniyorum": "I'm learning Arabic",
  "İngilizce konuşuyor musun?": "Do you speak English?",
  "Ne demek?": "What does it mean?",
  "Bana yardım et": "Help me",
  "Önemli değil": "It doesn't matter",
  "Boş ver / olsun": "Never mind / it's OK",
  "Allah razı olsun": "May God bless you",

  // ----- Hafta 4 -----
  "Gittim": "I went",
  "Yedim": "I ate",
  "İçtim": "I drank",
  "Gördüm": "I saw",
  "Dün ne yaptın?": "What did you do yesterday?",
  "Evdeydim": "I was at home",
  "Satın aldım": "I bought",
  "Arkadaşımla buluştum": "I met my friend",
  "Film izledim": "I watched a movie",
  "Erken uyudum": "I slept early",
  "Gideceğim": "I will go",
  "Yapacağım": "I will do",
  "Yarın görüşürüz": "See you tomorrow",
  "Randevum var": "I have an appointment",
  "Seni arayacağım": "I will call you",
  "Planların ne?": "What are your plans?",
  "Gelecek ay seyahate çıkacağım": "I'm traveling next month",
  "Gelecek hafta": "Next week",
  "Sonra": "Later",
  "Bekliyorum": "I'm waiting",
  "Ne haber?": "What's up?",
  "Her şey yolunda": "Everything is fine",
  "Peki tamam": "Alright then",
  "Süperim (yasemin gibi)": "I'm great (like jasmine)",
  "Güzel bir şey": "A beautiful thing",
  "İnanılmaz / olamaz": "Unbelievable / no way",
  "Kendine iyi bak": "Take care of yourself",
  "Seni özledim": "I missed you",
  "Selamün aleyküm": "Peace be upon you (hello)",
  "Aleyküm selam (cevap)": "And peace upon you (reply)",
  "Kolay gelsin (çok yaygın)": "May God give you strength (very common)",
  "Kardeşim (hitap)": "My brother (addressing)",
  "Tamam / emredersin": "OK / at your command",
  "Başım üstüne": "With pleasure (on my head)",
  "Allah kolaylık versin": "May God make it easy",
  "Keyfine bak / rahatına": "As you like / take it easy",
  "Yüzde yüz / harika": "Hundred percent / perfect",
  "Doğru / bu arada": "True / by the way",
  "Nasılsın? Ne yapıyorsun?": "How are you? What are you doing?",
  "Çok şükür, iyiyim": "Thank God, I'm fine",
  "Şehir merkezine gitmek istiyorum": "I want to go downtown",
  "Bugün hava güzel": "The weather is nice today",
  "Ne içmek istersin?": "What would you like to drink?",
  "Riyad'da yaşıyorum": "I live in Riyadh",
  "Bir soru sorabilir miyim?": "May I ask a question?",
  "İnşallah yine görüşürüz": "Hopefully we'll meet again",
  "Görüşmek üzere": "See you soon",
  "İyi geceler": "Good night",

  // ----- Hafta 5 (İş) -----
  "Ben yeni çalışanım": "I'm the new employee",
  "Şirket": "Company",
  "Ofis": "Office",
  "Müdür": "Manager",
  "İş arkadaşı (erkek için)": "Colleague (male)",
  "İş arkadaşı (kadın için)": "Colleague (female)",
  "İş": "Work / job",
  "Mühendis olarak çalışıyorum (kadın söyler)": "I work as an engineer (woman speaking)",
  "Tanıştığımıza memnun oldum": "Pleased to meet you",
  "Umarım iyi çalışırız birlikte": "I hope we work well together",
  "Toplantı": "Meeting",
  "Yarın toplantımız var": "We have a meeting tomorrow",
  "Saat kaçta?": "At what time?",
  "Sabah saat onda": "At ten in the morning",
  "Randevu": "Appointment",
  "Geç kalmış": "Late",
  "Geciktiğim için üzgünüm": "Sorry for being late",
  "Başlayalım mı?": "Shall we start?",
  "Bir sorum var": "I have a question",
  "Anlaştık": "Agreed / deal",
  "Bana yardım edebilir misin?": "Can you help me?",
  "Bana e-posta gönder": "Send me an email",
  "Sana dosyayı göndereceğim": "I'll send you the file",
  "İşi bitirdim": "I finished the work",
  "Daha fazla zamana ihtiyacım var": "I need more time",
  "Proje": "Project",
  "Rapor": "Report",
  "Böyle tamam mı?": "Is it OK like this?",
  "Mükemmel iş": "Excellent work",
  "Mola": "Break",
  "Alo": "Hello (phone)",
  "Kiminle görüşüyorum?": "Who am I speaking with?",
  "Bir saniye": "One second",
  "Kendisi yerinde yok": "He's not available",
  "Sonra tekrar ara": "Call again later",
  "Sizi arayacağım (kibarca)": "I will call you (politely)",
  "Telefon numaran kaç?": "What's your phone number?",
  "Mesaj gönderebilir misin?": "Can you send a message?",
  "Mesaj ulaştı": "The message arrived",
  "Zamanın için teşekkürler": "Thanks for your time",
  "Siz (kibar hitap)": "You (polite address)",
  "Affedersiniz beyefendi": "Excuse me, sir",
  "Hanımefendi (hitap)": "Madam (addressing)",
  "Zahmet olmazsa": "If it's no trouble",
  "Emrinizdeyim": "At your service",
  "Sakıncası yok": "No objection",
  "İzin / tatil": "Leave / vacation",
  "Yarın izin istiyorum (kadın söyler)": "I want a day off tomorrow (woman speaking)",
  "Maaş": "Salary",
  "Allah başarı versin": "May God grant you success",

  // ----- Diyaloglar -----
  "☕ Kafede Sipariş": "☕ Ordering at a Café",
  "🚕 Takside": "🚕 In a Taxi",
  "💼 Ofiste İlk Gün": "💼 First Day at the Office",
  "🤝 Toplantıda": "🤝 In a Meeting",
  "Kolay": "Easy",
  "Orta": "Medium",
  "Garson": "Waiter",
  "Şoför": "Driver",
  "İş arkadaşı": "Colleague",
  "Merhaba, ne içmek istersin?": "Hello, what would you like to drink?",
  "Kahve istiyorum lütfen": "I'd like a coffee, please",
  "Şekerli mi şekersiz mi?": "With or without sugar?",
  "Tamam, bir saniye": "OK, one second",
  "Nereye gidiyorsun?": "Where are you going?",
  "Tamam, buyur": "OK, come in",
  "Kaça?": "How much?",
  "Elli riyal": "Fifty riyals",
  "Çok pahalı! Otuz olur mu?": "Too expensive! How about thirty?",
  "Tamam dostum": "OK, my friend",
  "Hoş geldin! Yeni çalışan sen misin?": "Welcome! Are you the new employee?",
  "Evet, ben Türkiye'denim": "Yes, I'm from Turkey",
  "Memnun oldum! Adın ne?": "Nice to meet you! What's your name?",
  "Adım Senem, memnun oldum": "My name is Senem, nice to meet you",
  "Çay içmek ister misin?": "Would you like some tea?",
  "Evet, teşekkürler": "Yes, thank you",
  "Umarım birlikte iyi çalışırız": "I hope we work well together",
  "Günaydın, başlayalım mı?": "Good morning, shall we start?",
  "Günaydın, tamam": "Good morning, OK",
  "Raporu bitirdin mi?": "Did you finish the report?",
  "Evet, sana dosyayı göndereceğim": "Yes, I'll send you the file",
  "Mükemmel iş!": "Excellent work!",
  "📦 Kurye Adresi Bulamadı": "📦 Courier Can't Find the Address",
  "💂 Güvenlik Kuryeyi İçeri Almıyor": "💂 Security Won't Let the Courier In",
  "🛵 Kapıda Teslimat ve Ödeme": "🛵 Delivery & Payment at the Door",
  "Kurye": "Courier",
  "Güvenlik": "Security guard",
  "Alo, ben kurye, adresi bulamıyorum": "Hello, I'm the courier, I can't find the address",
  "Şu an neredesin?": "Where are you right now?",
  "Ana kapının önündeyim": "I'm in front of the main gate",
  "Tamam, sağa gir sonra düz devam et": "OK, turn right then go straight",
  "Bina numarası kaç?": "What's the building number?",
  "Beş numaralı bina, ikinci kat": "Building number five, second floor",
  "Tamam, iki dakikaya geliyorum": "OK, I'll be there in two minutes",
  "Tamam, seni bekliyorum": "OK, I'm waiting for you",
  "Sorun var, kurye izinsiz giremez": "There's a problem, the courier can't enter without a permit",
  "Neden? Bana yemek getiriyor": "Why? He's bringing me food",
  "Kurallar böyle, izin lazım": "Those are the rules, a permit is needed",
  "Peki inip kendim teslim alabilir miyim?": "OK, can I come down and pick it up myself?",
  "Evet tabii, buyur": "Yes of course, go ahead",
  "Teşekkürler, bir dakikada geliyorum": "Thanks, I'll be down in a minute",
  "İyi akşamlar, sipariş senin adına mı?": "Good evening, is the order under your name?",
  "Evet, bu benim siparişim": "Yes, this is my order",
  "Hesap yüz elli": "The total is one hundred fifty",
  "Evet, buyur cihaz": "Yes, here's the card machine",
  "Buyur, bu da senin (bahşiş)": "Here you go, and this is for you (tip)",
  "Çok teşekkürler efendim!": "Thank you very much, sir/madam!",

  // ----- Cep Rehberi -----
  "🚨 Acil Durum": "🚨 Emergency",
  "🚕 Taksi ve Yol": "🚕 Taxi & Directions",
  "🍽️ Restoran": "🍽️ Restaurant",
  "🛍️ Alışveriş": "🛍️ Shopping",
  "💼 Ofis": "💼 Office",
  "🙏 Nezaket": "🙏 Politeness",
  "Bana yardım edin!": "Help me!",
  "Ambulans çağırın": "Call an ambulance",
  "Polis çağırın": "Call the police",
  "Kayboldum": "I'm lost",
  "Hastayım, doktora ihtiyacım var": "I'm sick, I need a doctor",
  "Pasaportum kayboldu": "I lost my passport",
  "En yakın hastane nerede?": "Where is the nearest hospital?",
  "Havalimanına gitmek istiyorum": "I want to go to the airport",
  "Burada durun lütfen": "Stop here, please",
  "Düz git": "Go straight",
  "Sağa": "To the right",
  "Sola": "To the left",
  "Taksimetreyi açın lütfen": "Turn on the meter, please",
  "Acelem var": "I'm in a hurry",
  "En iyi yemeğiniz ne?": "What's your best dish?",
  "Et yemiyorum": "I don't eat meat",
  "Acısız olsun": "Not spicy, please",
  "Maden suyu / şişe su lütfen": "Bottled water, please",
  "Yemek çok lezzetli": "The food is delicious",
  "Çok pahalı, biraz indirin": "Too expensive, lower it a bit",
  "Deneyebilir miyim?": "Can I try it on?",
  "Daha büyük bedeni var mı?": "Do you have a bigger size?",
  "Bunu alıyorum": "I'm taking this",
  "Kartla ödeyebilir miyim?": "Can I pay by card?",
  "Sadece bakıyorum": "I'm just looking",
  "Sizi sonra arayacağım": "I'll call you later",
  "Bana e-posta gönderin lütfen": "Please send me an email",
  "Toplantımız ne zaman?": "When is our meeting?",
  "Daha fazla zamana ihtiyacım var (kadın söyler)": "I need more time (woman speaking)",
  "İyi Arapça konuşamıyorum": "I don't speak Arabic well",
  "Tekrar söyler misiniz?": "Could you say that again?",
  "Çok teşekkür ederim": "Thank you very much",
  "Kusura bakmayın, üzgünüm": "Pardon me, I'm sorry",
  "İzninizle": "With your permission",

  // ----- Hedefler ve seviyeler -----
  "Günün dersini bitir": "Finish today's lesson",
  "1 quiz çöz (en az %60)": "Take 1 quiz (at least 60%)",
  "3 kelimeyi mikrofonla doğru oku": "Say 3 words correctly with the mic",
  "10 kelimeyi sesli dinle": "Listen to 10 words",
  "Yeni Başlayan": "Beginner",
  "Turist": "Tourist",
  "Sokak Bilgesi": "Street Smart",
  "Pazarlık Ustası": "Bargain Master",
  "Sohbet Ehli": "Conversationalist",
  "Ofis Profesyoneli": "Office Pro",
  "Arapça Uzmanı": "Arabic Expert",
  "Yarı Arap": "Half Arab"
};

// ----- Arayüz metinleri -----
const UI_METIN = {
  tr: {
    tab_bugun: "Bugün", tab_ders: "Ders", tab_pratik: "Pratik", tab_konus: "Konuş",
    tab_ceviri: "Çeviri", tab_rehber: "Rehber", tab_plan: "Plan",
    gunluk_hedefler: "Günlük Hedefler", dakika: "(~15 dakika)",
    gunun_kelimesi: "Günün Kelimesi", tekrar_zamani: "Tekrar Zamanı 🃏",
    gunun_dersi: "Günün Dersi — Hafta", derse_basla: "Derse Başla", tekrar_et: "Tekrar Et",
    gun_tamam: "🎉 <b>Mabruuk!</b> (Tebrikler!) Bugünün tüm hedeflerini tamamladın!",
    pratik: "🧠 Pratik", konusma: "🎤 Konuşma",
    anlam_quiz: "Anlam Quizi", anlam_quiz_alt: "Okunuşu gör, anlamı seç",
    dinleme_quiz: "Dinleme Quizi", dinleme_quiz_alt: "Sesi dinle, anlamı seç",
    eslestirme: "Eşleştirme", eslestirme_alt: "Okunuş ↔ anlam eşleştir",
    flashcard: "Flashcard Tekrarı", flashcard_alt: "Akıllı tekrar (zorlandıkların)",
    telaffuz: "Telaffuz Pratiği", telaffuz_alt: "Seans modu: 10 kelime, söyle ve puan topla",
    diyalog: "Sesli Diyalog", diyalog_alt: "Uygulamayla konuş!",
    cevirmen: "🌐 Çevirmen",
    cevirmen_ipucu: "Cümleni yaz ya da söyle — çevirir, okunuşunu yazar, sesli okur.",
    yon_kaynak_ar: "Türkçe → Arapça", yon_ar_kaynak: "Arapça → Türkçe",
    ceviri_placeholder: "Çevrilecek Türkçe cümleni yaz... ya da 🎤 ile söyle",
    ceviri_placeholder_ar: "Arapça söyle 🎤 (ya da Arapça yaz)",
    soyle: "🎤 Söyle", cevir: "Çevir", cevriliyor: "Çevriliyor...", ceviri_etiket: "Çeviri:",
    dinle: "🔊 Dinle", sen_soyle: "🎤 Sen Söyle",
    okunus_not: "Türkçe okunuş (yaklaşık) — 🔊 ile gerçek sesi dinle",
    rehber: "🆘 Cep Rehberi",
    rehber_ipucu: "Gerçek hayatta sıkışınca: ifadeye dokun, telefon senin yerine Arapça söylesin! 📢",
    yol_haritasi: "🗓️ Yol Haritası", rozetler: "🏅 Rozetler", istatistikler: "📊 İstatistikler",
    ayarlar: "⚙️ Ayarlar", arapca_goster: "Arapça yazıyı da göster", karanlik: "🌙 Karanlık mod",
    dil: "Dil / Language:", hiz: "Konuşma hızı:", ses: "Arapça ses:",
    openai_anahtar: "OpenAI API anahtarı (isteğe bağlı — çok daha doğal ses):",
    openai_ipucu: "platform.openai.com'dan anahtar al, buraya yapıştır. Boşsa tarayıcı sesi kullanılır.",
    sifirla: "İlerlemeyi Sıfırla", kapat: "Kapat",
    hafta: "Hafta", ac: "Aç", geri: "← Geri", cik: "← Çık",
    soru: "Soru", dogru: "Doğru", yeni_quiz: "Pratik Menüsü",
    ders_ipucu: "🔊 dinle, 🎤 kendin söyle ve telaffuzunu test et.",
    dersi_bitir: "Dersi Bitir ✓", ders_bitti: "✅ Bu dersi bitirdin",
    dinliyorum: "👂 Dinliyorum... şimdi konuş! (bitince kendiliğinden durur, istersen 🎤'a tekrar bas)",
    duydugum: "Duyduğum:",
    quiz_soru_ipucu: "Bu ifadenin anlamı hangisi?",
    dinleme_ipucu: "Sesi dinle — anlamı hangisi?",
    esl_ipucu: "Okunuş ile anlamı eşleştir 🧩",
    tum_dersler: "🌟 Tüm Dersler (karışık)",
    xp_ders: "Günün dersi bitti", xp_quiz: "Quiz tamamlandı", xp_konusma: "Konuşma hedefi tamam",
    xp_dinleme: "Dinleme hedefi tamam", xp_gun: "Günlük hedefler tamamlandı! 🔥",
    xp_yeniders: "Yeni ders bitti", xp_skor: "Quiz skoru", xp_esl: "Eşleştirme bitti",
    xp_fc: "Flashcard tekrarı", xp_dlg: "Diyalog tamamlandı", xp_dlg2: "Diyalog tekrarı",
    seviye_atla: "SEVİYE ATLADIN", rozet_yeni: "Yeni rozet",
    kalan_xp: "seviyesine {n} XP kaldı", ust_seviye: "En üst seviyedesin! 👑",
    mukemmel: "Mumteez! (Mükemmel!)", iyi: "Kuveyyis! (İyi!)", tekrar_dene: "Tekrar dene — meeşi? (tamam mı?)",
    esl_sonuc: "Hepsini <b>{n} saniyede</b> eşleştirdin!",
    fc_bitti: "Tekrar bitti! {n} kart gözden geçirdin.",
    fc_on: "Arapçasını hatırla, karta dokun 👆", bildim: "😎 Bildim", bilemedim: "😵 Bilemedim",
    fc_akilli: "— 🧠 akıllı tekrar", fc_rastgele: "— rastgele tekrar",
    srs_bekleyen: "<b>{n} kelime</b> tekrar bekliyor — zorlandığın kelimeleri unutma!",
    srs_basla: "🃏 Tekrara Başla",
    srs_yok: "✨ Bekleyen tekrar yok. Quiz çözdükçe zorlandığın kelimeler buraya düşer.",
    dlg_baslik: "💬 Sesli Diyalog — uygulamayla konuş!",
    dlg_ipucu: "Karşındaki konuşur (sesli), sıra sana gelince repliğini mikrofonla söylersin.",
    replik: "replik", dlg_sira: "🎬 Sıra sende! Şunu söyle:",
    ipucu_btn: "🔊 İpucu", gec: "⏭️ Geç",
    dlg_tamamlandi: "🎭 <b>Mumteez!</b> Diyaloğu tamamladın!", dlg_don: "Diyaloglara Dön", sen: "Sen",
    dlg_yanlis: "%{s} — bir daha dene! 🔊 İpucu'ya basıp dinleyebilirsin.",
    tel_iyi: "🎉 Harika! <b>%{s}</b> doğruluk — \"{w}\" telaffuzun çok iyi!",
    tel_orta: "👍 Fena değil: <b>%{s}</b>. 🔊 ile bir kez daha dinle ve tekrar dene: \"<b>{w}</b>\"",
    tel_kotu: "🔄 <b>%{s}</b> — olmadı ama sorun değil! 🔊 ile dinle, sonra tekrar söyle: \"<b>{w}</b>\"",
    err_destek: "⚠️ Bu tarayıcı sesli tanımayı desteklemiyor.<br>📱 Android'de <b>Chrome</b>, iPhone'da <b>Safari</b> kullan. iPhone'da Ayarlar → Genel → Klavye → Dikte açık olmalı.",
    err_izin: "🎙️ Mikrofon izni gerekli. Tarayıcı adres çubuğundaki kilit simgesinden mikrofona izin ver.",
    err_ses_yok: "🤫 Ses duyamadım. Mikrofona biraz daha yakın ve yüksek sesle konuş.",
    err_ag: "📡 Ağ hatası — ses tanıma için internet gerekiyor.",
    err_dil: "Bu cihaz Arapça tanımayı desteklemiyor.",
    err_baslat: "Mikrofon başlatılamadı, sayfayı yenileyip tekrar dene.",
    err_duyamadim: "🤔 Bir şey duyamadım. Mikrofon tuşuna bas, \"dinliyorum\" yazısını görünce konuş.",
    err_hata: "Tanıma hatası:",
    cev_once: "Önce bir cümle yaz ya da söyle.",
    cev_hata: "⚠️ Çeviri yapılamadı. İnternet bağlantını kontrol et.",
    cev_yon_uyari: "Önce Arapçaya bir çeviri yap.",
    oai_hata: "OpenAI sesi çalışmadı — tarayıcı sesi kullanılıyor. Anahtarını kontrol et.",
    oai_stt_hata: "⚠️ Ses çözümlenemedi. OpenAI anahtarını ve internetini kontrol et.",
    cozumleniyor: "🤖 Söylediğini çözümlüyorum...",
    ses_bulunamadi: "Arapça ses bulunamadı — cihaza Arapça TTS ekleyin",
    sifir_onay: "Tüm ilerlemen (XP, seri, biten dersler) silinecek. Emin misin?",
    ders_tekrar_toast: "Bu ders zaten tamam — tekrar etmek süper! 💪",
    selam_sabah: "Sabaah il-hêr! ☀️ (Günaydın!)", selam_gun: "Ehlen! 👋 (Merhaba!)", selam_aksam: "Mesee' il-hêr! 🌙 (İyi akşamlar!)",
    hiz_turu: "Hız Turu", hiz_turu_alt: "60 saniyede kaç doğru?",
    sayi_antrenor: "Sayı Antrenörü", sayi_antrenor_alt: "Fiyatları ve sayıları öğren",
    sure: "Süre", skor: "Skor",
    hiz_bitti: "⚡ Süre doldu! <b>{n} doğru</b> yaptın!",
    sayi_cevir_ipucu: "Bir sayı yaz (0-999), Arapça okunuşunu öğren:",
    sayi_quiz_ipucu: "Bu sayı Arapça nasıl okunur?",
    ders_dinle: "▶️ Tüm Dersi Dinle", ders_dinle_dur: "⏹️ Durdur",
    xp_hiz: "Hız turu", xp_sayi: "Sayı antrenmanı", xp_tel: "Telaffuz seansı",
    tel_ozet: "Seans bitti! Ortalama doğruluk: %{n}", tel_tekrar: "🔄 Yeni Seans",
    stat_seviye: "Seviye", stat_seri: "Günlük seri", stat_gun: "gün", stat_xp: "Toplam XP",
    ai_hoca: "AI Hoca (ChatGPT)", ai_hoca_alt: "Gerçek sohbet — o Arapça cevap verir, sesiyle okur",
    ai_anahtar_gerek: "🤖 AI Hoca için ⚙️ Ayarlar'a OpenAI API anahtarını girmen gerekiyor (platform.openai.com'dan alınır).",
    ai_placeholder: "Mesajını yaz (Türkçe de olur)... ya da 🎤 ile Arapça söyle",
    ai_gonder: "Gönder", ai_dusunuyor: "🤖 düşünüyor...",
    ai_hata: "⚠️ AI cevabı alınamadı. Anahtarını ve internet bağlantını kontrol et.",
    ai_hosgeldin: "Ehlen! Ben senin Arapça hocanım 🤖 Bana Türkçe yazabilir ya da 🎤 ile Arapça konuşabilirsin; ben hep Mısır Arapçasıyla cevap verip okunuşunu ve anlamını gösteririm. Yalla, başlayalım — izzeyyik?",
    ai_hoca_adi: "AI Hoca",
    alt_baslik: "🔁 Aynı anlama gelen başka söyleyişler:",
    alt_anahtar: "💡 Alternatif söyleyişler için ⚙️ Ayarlar'a OpenAI anahtarını girmelisin.",
    alt_hata: "⚠️ Alternatifler alınamadı — internet ve anahtarını kontrol et.",
    yukleniyor: "⏳ Hazırlanıyor...",
    ai_ipucu_baslik: "💡 Şöyle cevap verebilirsin:",
    ai_ipucu_gonder: "➤ Bunu söyle",
    cev_alt: "💡 Alternatifler", cev_analiz: "🔍 Kelime Kelime",
    canli: "🎙️ Canlı Tercüman",
    canli_ipucu: "Takside, toplantıda: karşı taraf konuşsun → sana çevirir; sen konuş → ona Arapça söyler. Konuşma bitince çeviri 3-5 saniyede gelir.",
    canli_onlar: "🗣️ O Konuşuyor (Arapça)",
    canli_ben: "🎤 Ben Konuşuyorum",
    canli_anahtar: "🎙️ Canlı Tercüman için ⚙️ Ayarlar'a OpenAI anahtarını girmelisin.",
    canli_o: "Karşı taraf", canli_sen: "Sen",
    analiz_baslik: "🔍 Kelime kelime çözümleme:",
    analiz_hata: "⚠️ Çözümleme alınamadı — internet ve anahtarını kontrol et.",
    yedek_al: "📥 Yedek Al", yedek_yukle: "📤 Yedek Yükle",
    yedek_kopyalandi: "Yedek panoya kopyalandı! Notlara yapıştırıp saklayabilirsin.",
    yedek_sor: "Yedek metnini buraya yapıştır:",
    yedek_hata: "Geçersiz yedek metni.",
    yedek_tamam: "Yedek yüklendi! Sayfa yenileniyor...",
    aktivite: "📆 Son 4 Hafta Aktiviten", paylas: "📤 İlerlemeni Paylaş",
    paylas_metin: "Saudi Survival App'te {xp} XP topladım, seviyem: {seviye}! 🏜️ Arapça öğreniyorum!",
    kopyalandi: "Panoya kopyalandı!"
  },
  en: {
    tab_bugun: "Today", tab_ders: "Lesson", tab_pratik: "Practice", tab_konus: "Speak",
    tab_ceviri: "Translate", tab_rehber: "Guide", tab_plan: "Plan",
    gunluk_hedefler: "Daily Goals", dakika: "(~15 minutes)",
    gunun_kelimesi: "Word of the Day", tekrar_zamani: "Review Time 🃏",
    gunun_dersi: "Today's Lesson — Week", derse_basla: "Start Lesson", tekrar_et: "Review",
    gun_tamam: "🎉 <b>Mabruuk!</b> (Congratulations!) You completed all of today's goals!",
    pratik: "🧠 Practice", konusma: "🎤 Speaking",
    anlam_quiz: "Meaning Quiz", anlam_quiz_alt: "See the word, pick the meaning",
    dinleme_quiz: "Listening Quiz", dinleme_quiz_alt: "Listen, pick the meaning",
    eslestirme: "Matching", eslestirme_alt: "Match word ↔ meaning",
    flashcard: "Flashcard Review", flashcard_alt: "Smart review (your hard words)",
    telaffuz: "Pronunciation", telaffuz_alt: "Session mode: 10 words, speak and score",
    diyalog: "Voice Dialogue", diyalog_alt: "Talk with the app!",
    cevirmen: "🌐 Translator",
    cevirmen_ipucu: "Type or say your sentence — it translates, writes the reading and speaks it.",
    yon_kaynak_ar: "English → Arabic", yon_ar_kaynak: "Arabic → English",
    ceviri_placeholder: "Type your English sentence... or say it with 🎤",
    ceviri_placeholder_ar: "Speak Arabic 🎤 (or type in Arabic)",
    soyle: "🎤 Speak", cevir: "Translate", cevriliyor: "Translating...", ceviri_etiket: "Translation:",
    dinle: "🔊 Listen", sen_soyle: "🎤 You Say It",
    okunus_not: "Phonetic reading (approximate) — tap 🔊 for the real sound",
    rehber: "🆘 Pocket Guide",
    rehber_ipucu: "Stuck in real life? Tap a phrase and your phone speaks Arabic for you! 📢",
    yol_haritasi: "🗓️ Roadmap", rozetler: "🏅 Badges", istatistikler: "📊 Statistics",
    ayarlar: "⚙️ Settings", arapca_goster: "Show Arabic script", karanlik: "🌙 Dark mode",
    dil: "Dil / Language:", hiz: "Speech rate:", ses: "Arabic voice:",
    openai_anahtar: "OpenAI API key (optional — much more natural voice):",
    openai_ipucu: "Get a key at platform.openai.com and paste it here. If empty, the browser voice is used.",
    sifirla: "Reset Progress", kapat: "Close",
    hafta: "Week", ac: "Open", geri: "← Back", cik: "← Exit",
    soru: "Question", dogru: "Correct", yeni_quiz: "Practice Menu",
    ders_ipucu: "🔊 listen, 🎤 say it yourself and test your pronunciation.",
    dersi_bitir: "Finish Lesson ✓", ders_bitti: "✅ Lesson completed",
    dinliyorum: "👂 Listening... speak now! (stops by itself, or tap 🎤 again)",
    duydugum: "I heard:",
    quiz_soru_ipucu: "What does this phrase mean?",
    dinleme_ipucu: "Listen — what does it mean?",
    esl_ipucu: "Match the word with its meaning 🧩",
    tum_dersler: "🌟 All Lessons (mixed)",
    xp_ders: "Daily lesson done", xp_quiz: "Quiz completed", xp_konusma: "Speaking goal done",
    xp_dinleme: "Listening goal done", xp_gun: "All daily goals completed! 🔥",
    xp_yeniders: "New lesson finished", xp_skor: "Quiz score", xp_esl: "Matching done",
    xp_fc: "Flashcard review", xp_dlg: "Dialogue completed", xp_dlg2: "Dialogue repeat",
    seviye_atla: "LEVEL UP", rozet_yeni: "New badge",
    kalan_xp: "{n} XP to reach", ust_seviye: "You're at the top level! 👑",
    mukemmel: "Mumtaaz! (Excellent!)", iyi: "Kuwayyis! (Good!)", tekrar_dene: "Try again — maashi? (OK?)",
    esl_sonuc: "You matched them all in <b>{n} seconds</b>!",
    fc_bitti: "Review done! You went through {n} cards.",
    fc_on: "Recall the Arabic, tap the card 👆", bildim: "😎 Got it", bilemedim: "😵 Missed it",
    fc_akilli: "— 🧠 smart review", fc_rastgele: "— random review",
    srs_bekleyen: "<b>{n} words</b> are waiting for review — don't forget your hard words!",
    srs_basla: "🃏 Start Review",
    srs_yok: "✨ No reviews pending. Words you struggle with in quizzes will appear here.",
    dlg_baslik: "💬 Voice Dialogue — talk with the app!",
    dlg_ipucu: "The other side speaks (out loud); when it's your turn, say your line into the mic.",
    replik: "lines", dlg_sira: "🎬 Your turn! Say this:",
    ipucu_btn: "🔊 Hint", gec: "⏭️ Skip",
    dlg_tamamlandi: "🎭 <b>Mumtaaz!</b> You completed the dialogue!", dlg_don: "Back to Dialogues", sen: "You",
    dlg_yanlis: "{s}% — try again! Tap 🔊 Hint to listen first.",
    tel_iyi: "🎉 Great! <b>{s}%</b> accuracy — your pronunciation of \"{w}\" is very good!",
    tel_orta: "👍 Not bad: <b>{s}%</b>. Listen once more with 🔊 and try again: \"<b>{w}</b>\"",
    tel_kotu: "🔄 <b>{s}%</b> — not quite, but no worries! Listen with 🔊, then say it again: \"<b>{w}</b>\"",
    err_destek: "⚠️ This browser doesn't support speech recognition.<br>📱 Use <b>Chrome</b> on Android or <b>Safari</b> on iPhone. On iPhone, enable Settings → General → Keyboard → Dictation.",
    err_izin: "🎙️ Microphone permission needed. Allow the mic via the lock icon in the address bar.",
    err_ses_yok: "🤫 I couldn't hear anything. Speak closer to the mic and a bit louder.",
    err_ag: "📡 Network error — speech recognition needs internet.",
    err_dil: "This device doesn't support Arabic speech recognition.",
    err_baslat: "Couldn't start the microphone; refresh the page and try again.",
    err_duyamadim: "🤔 I didn't hear anything. Tap the mic and speak when you see \"listening\".",
    err_hata: "Recognition error:",
    cev_once: "Type or say a sentence first.",
    cev_hata: "⚠️ Translation failed. Check your internet connection.",
    cev_yon_uyari: "Translate something into Arabic first.",
    oai_hata: "OpenAI voice failed — using browser voice. Check your key.",
    oai_stt_hata: "⚠️ Couldn't transcribe the audio. Check your OpenAI key and internet.",
    cozumleniyor: "🤖 Analyzing what you said...",
    ses_bulunamadi: "No Arabic voice found — add an Arabic TTS voice to your device",
    sifir_onay: "All your progress (XP, streak, finished lessons) will be deleted. Are you sure?",
    ders_tekrar_toast: "This lesson is already done — reviewing is great! 💪",
    selam_sabah: "Sabaah il-kheir! ☀️ (Good morning!)", selam_gun: "Ahlan! 👋 (Hello!)", selam_aksam: "Masaa' il-kheir! 🌙 (Good evening!)",
    hiz_turu: "Speed Round", hiz_turu_alt: "How many in 60 seconds?",
    sayi_antrenor: "Number Trainer", sayi_antrenor_alt: "Learn prices and numbers",
    sure: "Time", skor: "Score",
    hiz_bitti: "⚡ Time's up! You got <b>{n} correct</b>!",
    sayi_cevir_ipucu: "Type a number (0-999) and learn its Arabic reading:",
    sayi_quiz_ipucu: "How is this number said in Arabic?",
    ders_dinle: "▶️ Play Whole Lesson", ders_dinle_dur: "⏹️ Stop",
    xp_hiz: "Speed round", xp_sayi: "Number training", xp_tel: "Pronunciation session",
    tel_ozet: "Session done! Average accuracy: {n}%", tel_tekrar: "🔄 New Session",
    stat_seviye: "Level", stat_seri: "Daily streak", stat_gun: "days", stat_xp: "Total XP",
    ai_hoca: "AI Tutor (ChatGPT)", ai_hoca_alt: "Real conversation — it replies in Arabic with voice",
    ai_anahtar_gerek: "🤖 The AI Tutor needs your OpenAI API key in ⚙️ Settings (get one at platform.openai.com).",
    ai_placeholder: "Type your message (English is fine)... or say it in Arabic with 🎤",
    ai_gonder: "Send", ai_dusunuyor: "🤖 thinking...",
    ai_hata: "⚠️ Couldn't get an AI reply. Check your key and internet connection.",
    ai_hosgeldin: "Ahlan! I'm your Arabic tutor 🤖 Write to me in English or speak Arabic with 🎤; I always reply in Egyptian Arabic with the reading and meaning. Yalla, let's start — izzayyik?",
    ai_hoca_adi: "AI Tutor",
    alt_baslik: "🔁 Other ways to say the same thing:",
    alt_anahtar: "💡 Alternative phrasings need your OpenAI key in ⚙️ Settings.",
    alt_hata: "⚠️ Couldn't fetch alternatives — check your key and internet.",
    yukleniyor: "⏳ Preparing...",
    ai_ipucu_baslik: "💡 You could reply like this:",
    ai_ipucu_gonder: "➤ Say this",
    cev_alt: "💡 Alternatives", cev_analiz: "🔍 Word by Word",
    canli: "🎙️ Live Interpreter",
    canli_ipucu: "In a taxi or meeting: let them speak → it translates for you; you speak → it says it in Arabic. Translation arrives 3-5 seconds after speech ends.",
    canli_onlar: "🗣️ They Speak (Arabic)",
    canli_ben: "🎤 I Speak",
    canli_anahtar: "🎙️ The Live Interpreter needs your OpenAI key in ⚙️ Settings.",
    canli_o: "Other side", canli_sen: "You",
    analiz_baslik: "🔍 Word-by-word breakdown:",
    analiz_hata: "⚠️ Couldn't get the breakdown — check your key and internet.",
    yedek_al: "📥 Backup", yedek_yukle: "📤 Restore",
    yedek_kopyalandi: "Backup copied to clipboard! Paste it into Notes to keep it safe.",
    yedek_sor: "Paste your backup text here:",
    yedek_hata: "Invalid backup text.",
    yedek_tamam: "Backup restored! Reloading...",
    aktivite: "📆 Your Last 4 Weeks", paylas: "📤 Share Your Progress",
    paylas_metin: "I earned {xp} XP in Saudi Survival App, my level: {seviye}! 🏜️ I'm learning Arabic!",
    kopyalandi: "Copied to clipboard!"
  }
};
